---
# File: main.yml - Default variables for Consul

## Core
consul_datacenter: "dc1"
consul_data_path: "/opt/consul"
consul_client_address: "0.0.0.0"
consul_ui: true
consul_bind_addr: {{ ansible_eth1.ipv4.address }}
consul_server: true
consul_bootstrap_expect: 3

